theme: jekyll-theme-minimal # Replace with your theme
title: Abhigna Reddy Musku
description: Welcome to my portfolio!

nav:
  - title: Home
    url: /
  - title: About Me
    url: /about/
  - title: Work Experience
    url: /experience/
  - title: Projects
    url: /projects/
  - title: Fun
    url: /fun/
